### ISSUE TITLE
iOS App Freezes on SDK initialization

### ISSUE THREAD

**Issue by nitanta** [BugBattle/iOS-SDK#6]
Device iPhone - 8
iOS Version - 14.3
SDK Version - 3.1.2
Xcode Version - 12.3

iOS App freezes on the first screen after the SDK is initialized.

Tried this with various other devices and simulators. Still facing the same issue

**Comment by boehlerlukas** [comment]
Hey @nitanta sorry for the late reply - i missed the GitHub notification. I will take a look asap.

**Comment by boehlerlukas** [comment]
Hey @nitanta we had a look today but couldn't reproduce the freeze yet. Did you try running our included demo? Is it freezing there as well? Can you try with the latest version 3.1.6 as well?

**Comment by GokmenAkar** [comment]
@boehlerlukas 

Hey,

`DYLD_PRINT_APIS = 1 
`

![image](https://user-images.githubusercontent.com/16048623/111483350-c60a7780-8745-11eb-8a64-feb863b73d30.png)

This will show where is a freezing on initialization, I don't know what causes this weird bug but at least when I don't initiate the bug battle I don't get stuck at the launching screen.

I hope it helps you find the issue guys. Have a nice day.

![image](https://user-images.githubusercontent.com/16048623/111483572-f3572580-8745-11eb-810d-56d811463b0c.png)

**Comment by boehlerlukas** [comment]
Hey @GokmenAkar thanks for your additional feedback - we will directly dive into it!

**Comment by boehlerlukas** [comment]
@GokmenAkar sorry for the late reply.

This should now be finally solved with our latest update v4.0.8. The issue was related to collecting the console log and occurs only when other libraries / SDKs are involved that do the same thing.

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  BugBattle (4.0.8) successfully published
 📅  July 9th, 13:11
 🌎  https://cocoapods.org/pods/BugBattle
 👍  Tell your friends!
--------------------------------------------------------------------------------

It would be awesome if you could have a look into it and let us know weather this issue has been solved.

**Comment by boehlerlukas** [comment]
Closed due to inactivity. The issue should be resolved.
